### ISSUE TITLE
missing epilepsy / seizure warning

### ISSUE THREAD

**Issue by breuerfelix** [brumhard/brumhard#1]
hey @brumhard, 
first of all, thanks for your contribution to the internet. your github profile page seems to make the internet a more pretty place after creating this repository. 

nontheless there should be an epilepsy / seizure warning on your page. to understand why, let me describe the journey for someone browsing github and landing on your page:

it is a casual wednesday afternoon while suddenly an issue on one of my repositories appears. of course there are plenty of programming newbies around here, so i first want to check the profile of the issue creator in order to know if i have to take this request seriously or can savely ignore / delete the issue to keep my beautiful repository clean.

"brumhard... hmm... his picture looks like the typical 'i studied BWL and watched a two hour python youtube tutorial so i am a programmer now' type of guy. better check out his repos / commits"

clicks on his name

his profile opens

"yep definetily a BWL guy, picture is even worse in 4k"

"ah nice he is welcoming me on this profile page"

"uhh some github stats appear smoothly on this page one by one"

"why do i have to press play on this gif here? could it be that hard to create a gif that autoplays? noob, must be pretty easy to program, maybe one of my next projects"

BOOOM GITHUB STARLINE APPEARS

"WHAT DA FUQ"

" I AM BROWSING THIS PAGE FOR ALMOST 7 SECONDS NOW"

"HOW CAN THE IMAGE LOAD BE THAT SLOW"

"i am gonna close his issue now. not gonna fix it anyways"

- the end

i mean in general this is not your fault, you are just consuming a tool which is badly written, maybe even in PHP, god bless.... and nothing really bad happened yet, i was able to handle this random flickering on a static website quite well.

you could open an issue on the corresponding repo or just create some trigger warning on your page.

cheers
felix

**Comment by brumhard** [comment]
Feelsbadman
